### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by emtiazzahid** [krzar/laravel-translation-generator#10]
Error

```composer require krzar/laravel-translation-generator -W
Using version ^3.0 for krzar/laravel-translation-generator
./composer.json has been updated
Running composer update krzar/laravel-translation-generator --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires krzar/laravel-translation-generator ^3.0 -> satisfiable by krzar/laravel-translation-generator[v3.0.0].
    - krzar/laravel-translation-generator v3.0.0 requires illuminate/console ^10.0 -> found illuminate/console[v10.0.0, ..., v10.48.8] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - outhebox/laravel-translations[1.1.0, ..., 1.1.1] require brick/varexporter ^0.4.0 -> satisfiable by brick/varexporter[0.4.0].  
    - brick/varexporter 0.4.0 requires nikic/php-parser ^4.0 -> found nikic/php-parser[v4.0.0, ..., v4.19.1] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires outhebox/laravel-translations ^1.1 -> satisfiable by outhebox/laravel-translations[1.1.0, 1.1.1].  

You can also try re-running composer require with an explicit version constraint, e.g. "composer require krzar/laravel-translation-generator:*" to figure out if any version is installable, or "composer require krzar/laravel-translation-generator:^2.1" if you know which you need.

**Comment by krzar** [comment]
Can you show your composer.json file content?

**Comment by emtiazzahid** [comment]
> Can you show your composer.json file content?

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "Laravel",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "akaunting/laravel-setting": "^1.2",
        "barryvdh/laravel-dompdf": "^2.0",
        "fakerphp/faker": "^1.9.1",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.7",
        "laravel/framework": "^11.0",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.9",
        "livewire/livewire": "^3.0",
        "orangehill/iseed": "^3.0",
        "simplesoftwareio/simple-qrcode": "^4.2",
        "jantinnerezo/livewire-alert": "^3.0",
        "realrashid/sweet-alert": "^7.1",
        "webklex/laravel-pdfmerger": "^1.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "fakerphp/faker": "^1.23",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.1",
        "phpunit/phpunit": "^11.0.1",
        "spatie/laravel-ignition": "^2.4"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        },
        "files": [
            "app/helpers.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi",
            "@php -r \"file_exists('database/database.sqlite') || touch('database/database.sqlite');\"",
            "@php artisan migrate --graceful --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true,
            "php-http/discovery": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

**Comment by krzar** [comment]
It should be already fixed with latest release
